django_blog/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [url(r'^signup/$', views.signup_view, name="signup")]

django_blog/articles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

django_blog/django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/accounts/models.py
from django.db import models

# Create your models here.

django_blog/articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    # add in thumbnail later
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:200] + ' ...'

django_blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

django_blog/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html',
                  {'articles': articles})


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',
                  {'article': article})

django_blog/django_blog/views.py
from django.http import HttpResponse 
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request,'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request,'about.html')

django_blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}
<!--  Block content -->
{%block content%}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  <!-- Validation token -->
  {%csrf_token%}
  <!-- UserCreation form -->
  {{form}}
  <input type="submit" value="Signup" />
</form>
{%endblock%}

django_blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}
<!-- Block of content -->
{%block content%}
<div class="article_detail">
  <div class="article">
    <img src="{{article.thumb.url}}" alt="" />
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{% endblock %}

django_blog/articles/templates/articles/article_list.html
{%extends 'base_layout.html'%} {%block content%}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2>
      <a href="{%url 'articles:detail' slug=article.slug %}"
        >{{article.title}}</a
      >
    </h2>
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
  </div>
  {% endfor%}
</div>
{% endblock %}

django_blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>We like Django</p>
  </body>
</html>

django_blog/templates/base_layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}" />
  </head>

  <body>
    <div class="wrapper">
      <h1>
        <a href="{% url 'articles:list'%} "
          ><img src="{%static 'django-logo.png'%}" alt=""
        /></a>
      </h1>
      {%block content%} {%endblock%}
    </div>
  </body>
</html>

django_blog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to Django Blog</p>
  </body>
</html>